import BarChart from '@/Components/BarChart'
import Header from '@/Components/Header'
import RecentOrders from '@/Components/RecentOrders'
import TopCards from '@/Components/TopCards'
import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-500 min-h-screen">
        <Header/>
        <TopCards/>
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <BarChart/>
          <RecentOrders/>
        </div>
        
      </main>
    </>
  )
}
